name: Setup Flutter
description: Setup Flutter
inputs:
  flutter-version:
    description: Flutter version
    default: 3.22.2
outputs:
  flutter-version:
    description: Flutter version
    value: ${{ inputs.flutter-version }}
runs:
  using: composite
  steps:
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter-version }}
        cache: true
